package cf.somwaki.medicalchat;

public class RemediesItemsList {
    public static final RemedyItem[] items = {
            new RemedyItem("1", "Take Care", "No matter what you've heard or how badly you want relief, talk with your doctor or pharmacist before trying any home remedy. This is even more important if you take prescription or over-the-counter medications, because some can affect how drugs work. And keep in mind that many don’t have any research to back them up."),
            new RemedyItem("2", "Peppermint", "Mint has been used for hundreds of years as a health remedy. Peppermint oil might help with irritable bowel syndrome -- a long-term condition that can cause cramps, bloating, gas, diarrhea, and constipation -- and it may be good for headaches as well. More studies are needed to see how much it helps and why. People use the leaf for other conditions, too, but there’s very little evidence it helps with any of them. "),
            new RemedyItem("3", "Honey", "This natural sweetener may work just as well for a cough as over-the-counter medicines. That could be especially helpful for children who aren’t old enough to take those. But don’t give it to an infant or a toddler younger than 1. There’s a small risk of a rare but serious kind of food poisoning that could be dangerous for them. And while you may have heard that “local” honey can help with allergies, studies don’t back that up."),
            new RemedyItem("4", "Turmeric", "This spice has been hyped as being able to help with a variety of conditions from arthritis to fatty liver. There is some early research to support this. Other claims, such as healing ulcers and helping with skin rashes after radiation are lacking proof. If you try it, don’t overdo it: High doses can cause digestive problems."),
            new RemedyItem("5", "Ginger", "It’s been used for thousands of years in Asian medicine to treat stomachaches, diarrhea, and nausea, and studies show that it works for nausea and vomiting. There’s some evidence that it might help with menstrual cramps, too. But it’s not necessarily good for everyone. Some people get tummy trouble, heartburn, diarrhea, and gas because of it, and it may affect how some medications work. So talk to your doctor, and use it with care."),
            new RemedyItem("6", "Green Tea", "This comforting drink does more than keep you awake and alert. It’s a great source of some powerful antioxidants that can protect your cells from damage and help you fight disease. It may even lower your odds of heart disease and certain kinds of cancers, like skin, breast, lung, and colon."),
            new RemedyItem("7", "Garlic", "Some studies show that people who eat more garlic are less likely to get certain types of cancer (garlic supplements don’t seem to have the same effect). It also may lower blood cholesterol and blood pressure levels, but it doesn’t seem to help that much."),
            new RemedyItem("8", "Chicken Soup", "Turns out, Grandma was right: Chicken soup can be good for a cold. Studies show it can ease symptoms and help you get rid of it sooner. It also curbs swelling and clears out nasal fluids."),
            new RemedyItem("9", "Neti Pot", "You put a salt and warm water mixture in something that looks like a little teapot. Then pour it through one nostril and let it drain out the other. You have to practice a little, but once you get the hang of it, it can ease allergy or cold symptoms and may even help you get rid of a cold quicker. Just make sure you use distilled or cooled boiled water and keep your neti pot clean. "),

    };
}
